-- 0006_reservations.sql
-- VP-8: demo appointment-reservation feature. Entirely fictional demo data,
-- generated by this project's own algorithmic availability logic — not
-- connected to any real clinic's booking system (see docs/FUTURE-FEATURES.md
-- and the VP-8 work order §1 decisions). Content (services, fake patients,
-- fake already-booked times) is seeded by `npm run demo:seed`, not by this
-- migration — this file only creates the schema.

-- A small, fixed list of bookable services. `id` is a slug (like a FAQ id),
-- not a uuid, so it reads naturally in the prompt and in a tool argument.
CREATE TABLE reservation_services (
  id                text        PRIMARY KEY,
  client_id         text        NOT NULL,
  name_ja           text        NOT NULL,
  name_en           text        NOT NULL,
  duration_minutes  integer     NOT NULL CHECK (duration_minutes > 0),
  sort_order        integer     NOT NULL DEFAULT 0,
  created_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX reservation_services_client_sort_idx ON reservation_services (client_id, sort_order);

-- Fake returning-patient records for the demo (same spirit as the "Yamada
-- Taro" test data used in VP-7). Matched by phone only (VP-8 decision 5) —
-- the caller's spoken name is used for a verbal confirmation, never as the
-- lookup key.
CREATE TABLE reservation_demo_patients (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id   text        NOT NULL,
  name        text        NOT NULL,
  phone       text        NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX reservation_demo_patients_client_phone_idx
  ON reservation_demo_patients (client_id, phone);

-- Fake "already booked" times pre-seeded so the algorithmic availability
-- check has something to say no to (VP-8 decision 4 — no real capacity
-- tracking, no concurrency handling).
CREATE TABLE reservation_booked_slots (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id   text        NOT NULL,
  slot_date   text        NOT NULL, -- YYYY-MM-DD
  slot_time   text        NOT NULL, -- HH:MM, 24-hour
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX reservation_booked_slots_client_date_time_idx
  ON reservation_booked_slots (client_id, slot_date, slot_time);

-- Completed demo bookings. service_id/service_name are null for a
-- returning-patient booking, which skips service selection (VP-8 §3).
-- service_name is a snapshot at booking time, independent of
-- reservation_services staying unchanged.
CREATE TABLE appointments (
  id                    uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id             text        NOT NULL,
  call_id               text        NOT NULL,
  language              text        NOT NULL,
  reservation_number    text        NOT NULL,
  service_id            text        REFERENCES reservation_services(id),
  service_name          text,
  patient_name          text        NOT NULL,
  patient_phone         text        NOT NULL,
  patient_email         text,
  is_returning_patient  boolean     NOT NULL DEFAULT false,
  appointment_date      text        NOT NULL, -- YYYY-MM-DD
  appointment_time      text        NOT NULL, -- HH:MM, 24-hour
  created_at            timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX appointments_client_reservation_idx
  ON appointments (client_id, reservation_number);
CREATE INDEX appointments_client_date_time_idx
  ON appointments (client_id, appointment_date, appointment_time);
