/**
 * GET /talk/:clientId/:language — a public, link-shareable page letting
 * anyone test the voice assistant via a browser mic call. No internal
 * config is exposed: just the clinic's own (already-public) name and a
 * Talk button.
 *
 * Unlike generateTestPage.ts's internal QA tool (pre-baked static files,
 * regenerated by hand after every `vapi:sync --apply`), this renders
 * dynamically per request straight from the current Vapi state file, so it
 * can never go stale.
 */
import { Router, type Request, type Response } from 'express';

import { ClientConfigError, loadClient } from '../config/loadClient.js';
import type { ClientConfig } from '../config/schema.js';
import { assistantResourceName } from '../vapi/squad.js';
import { readState } from '../vapi/stateStore.js';
import { renderTalkBootstrapScript, renderTalkPage } from '../vapi/talkPage.js';

export const TALK_URL_PREFIX = '/talk';

export interface TalkRouterOptions {
  /** Vapi's public key — safe to expose in the browser (VAPI-FACTS.md). */
  publicKey: string;
  /** Overrides for tests: where the client configs / Vapi state files are resolved from. */
  clientsDir?: string;
  repoRoot?: string;
}

interface ResolvedTarget {
  config: ClientConfig;
  assistantId: string;
}

/** Undefined for any reason at all — an unknown clientId, an unsupported language, or a language never synced. */
function resolveTarget(
  clientId: string,
  language: string,
  options: TalkRouterOptions,
): ResolvedTarget | undefined {
  let config: ClientConfig;
  try {
    config = loadClient(clientId, options.clientsDir ? { clientsDir: options.clientsDir } : {});
  } catch (error) {
    if (error instanceof ClientConfigError) return undefined;
    throw error;
  }

  if (!config.languages.supported.includes(language)) return undefined;

  const state = readState(clientId, options.repoRoot ? { repoRoot: options.repoRoot } : {});
  const assistantId = state.assistants[assistantResourceName(clientId, language)];
  if (!assistantId) return undefined;

  return { config, assistantId };
}

/** rules.ts's languageIssues check guarantees business.name has every supported language on a validated config. */
function clinicNameOf(config: ClientConfig, language: string): string {
  const name = config.business.name[language];
  if (!name) {
    throw new Error(`business.name missing "${language}" despite passing validation — config bug`);
  }
  return name;
}

function pagePath(clientId: string, language: string): string {
  return `${TALK_URL_PREFIX}/${clientId}/${language}`;
}

export function talkRouter(options: TalkRouterOptions): Router {
  const router = Router();

  router.get('/:clientId/:language', (req: Request, res: Response, next) => {
    const { clientId, language } = req.params as { clientId: string; language: string };
    const resolved = resolveTarget(clientId, language, options);
    if (!resolved) {
      next();
      return;
    }

    const switchLinks = resolved.config.languages.supported
      .filter((code) => code !== language)
      .map((code) => ({
        label: clinicNameOf(resolved.config, code),
        href: pagePath(clientId, code),
      }));

    res.type('html').send(
      renderTalkPage({
        clinicName: clinicNameOf(resolved.config, language),
        language,
        switchLinks,
        scriptSrc: `${pagePath(clientId, language)}/bootstrap.js`,
      }),
    );
  });

  router.get('/:clientId/:language/bootstrap.js', (req: Request, res: Response, next) => {
    const { clientId, language } = req.params as { clientId: string; language: string };
    const resolved = resolveTarget(clientId, language, options);
    if (!resolved) {
      next();
      return;
    }

    res
      .type('application/javascript')
      .send(
        renderTalkBootstrapScript({
          publicKey: options.publicKey,
          assistantId: resolved.assistantId,
        }),
      );
  });

  return router;
}
